[package]
name = "fsck_qrfs"
version = "0.1.0"
authors = []
edition = "2018"

[dependencies]
fuse = "0.3.1"
libc = "0.2.51"
time = "0.1.42"
serde = { version = "1.0", features = ["derive"] }
bincode = "1.1.3"
serde-big-array = "0.1.5"
qrcode-generator = "4.1.6"
image = "0.24.2"